// <auto-generated />
using System;
using ConsultationApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsultationApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251002064220_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ConsultationApp.Models.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsultantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Consultations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            ConsultantId = 1,
                            DateTime = new DateTime(2025, 4, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "booked"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            ConsultantId = 1,
                            DateTime = new DateTime(2025, 4, 6, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "booked"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
